# Generated by Django 3.2.3 on 2021-09-04 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bugCode', models.CharField(blank=True, max_length=10, null=True)),
                ('mainFeature', models.CharField(blank=True, max_length=20, null=True)),
                ('subFeature', models.CharField(blank=True, max_length=100, null=True)),
                ('bugTitle', models.CharField(blank=True, max_length=512, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('steps', models.TextField(blank=True, null=True)),
                ('expected', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('projectFolder', models.CharField(blank=True, max_length=255, null=True)),
                ('discoveredBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bugDiscoveredBy', to=settings.AUTH_USER_MODEL)),
                ('resolvedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bugResolvedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
